### PR TITLE
FINCN-165: Enhance Fineract CN startup script. make it work with mac and linux.

### PR DESCRIPTION
**Pull request by aasaru**
This combines #2 and #3. I haven't yet figured out how I can accept pull requests. I did all the steps @awasum suggested here: https://github.com/apache/fineract-cn-fims-web-app/pull/20#issuecomment-528415863 but still I don't see any "Merge" buttons next to PR-s.

@Anh3h I tested your PR with Mac and it didn't work. So I made the necessary adjustments so it could work both on Mac and Linux. I changed the IP addresses a bit to make them match the ports. So provisioner for example has port 2020 so it makes sense to assign ip that ends with .20 to it and so on. This way it is easier to remember.

I think we could do both - provide a script for provisioning and also manual instructions. The goal eventually is to make anyone understand what needs to be done - so the more instructions the better I think.

### CODE REVIEW

**Comment by cnangeh** [comment]
> This combines #2 and #3. I haven't yet figured out how I can accept pull requests. I did all the steps @awasum suggested here: apache/fineract-cn-fims-web-app#20 (comment) but still I don't see any "Merge" buttons next to PR-s.

@aasaru I also faced the same issue. Make your GitHub account uses two-factor authentication.

> @Anh3h I tested your PR with Mac and it didn't work. So I made the necessary adjustments so it could work both on Mac and Linux. I changed the IP addresses a bit to make them match the ports. So provisioner, for example, has port 2020 so it makes sense to assign ip that ends with .20 to it and so on. This way it is easier to remember.
I think we could do both - provide a script for provisioning and also manual instructions. The goal eventually is to make anyone understand what needs to be done - so the more instructions the better I think.

Yea.
When this feature gets merged, I think we could look at providing more detailed instructions (alongside images) of the provisioning process. It think it will be easier for contributors to follow.

**Comment by awasum** [comment]
Is this all ready to be merged?

**Comment by awasum** [comment]
@Anh3h , have a call with Juhan to see how to fix his lack of write access to Fineract Github problem.

**Comment by aasaru** [comment]
Yes. Please merge.

**Comment by aasaru** [comment]
I switched on 2FA but it did’t help

**Comment by cnangeh** [comment]
I made a review on this PR that highlighted the fact that cheques-ms is referencing the wrong docker images. It references reporting instead of cheques.
Since this PR has been merged with this bug, I have created an issue on Jira: https://issues.apache.org/jira/browse/FINCN-176 so that this bug should be fixed.

**Pull request merged**
