### PR TITLE
Add: Helm Chart Configurations for Fineract CN

### PR DESCRIPTION
**Pull request by BLasan**
Added helm configurations to deploy microservices on Kubernetes

### CODE REVIEW

**Comment by BLasan** [comment]
@avikganguly01 @fynmanoj Please review

**Comment by fynmanoj** [comment]
Please add the generated files to .gitignore .  we dont need to track generated files

**Comment by BLasan** [comment]
> Please add the generated files to .gitignore . we dont need to track generated files

Done

**Comment by avikganguly01** [comment]
@fynmanoj : Pleasw review.

**Comment by fynmanoj** [comment]
@BLasan remove generated files

**Review by avikganguly01 — CHANGES_REQUESTED** [review]
@BLasan The code diff doesn't look right. You're taking credit for other folks' work by duplicating code which is not cool. All the files in Kubernetes folder could have been just moved to the template folder. Please fix this so that this can be reviewed.

**Pull request merged**
